from time import sleep

for c in range(10, 0, -1):
    print(c)
    sleep(1)
print('FIIIIIIIIIIIIIIIIUUUUUUUUUUUUUUUUU')
sleep(1)
print('TRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRATRAT'
      'RATRATRATRA PUUUUUUUUUUUUUUU')
sleep(1)
print('PAPAPAPAAPAPAPAPAPAPOOOOOWWWWWW')
sleep(1)
print('POOOOOOOWWW POOOOWWW TRATRATRATRATRATRONNNHH ÃÃÃÃNN ÕÕÕÕÕH ÕÕÃÃÃNNHH ÃÃÃÃÃN ÕNNNHH AAÃÃÃNN ÕÕÕH ÃÃÃÃÃN ONNNH '
      'ONNNHH ÃÃÃÃNN ÕÕÕÕÕH ÕÕÃÃÃNNHH ÃÃÃÃÃN ÕNNNHH AAÃÃÃNH')
